name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set Up Docker
      uses: docker/setup-buildx-action@v1

    - name: Remove Running Container
      run: | 
        sudo docker kill cicd_container && sudo docker container prune --force
      continue-on-error: true

    - name: Build Docker Image
      run: |
        sudo docker build -t simple-ci-cd-project .

    - name: Deploy Application
      run: |
        sudo docker run -d -p 80:3000 --name cicd_container simple-ci-cd-project
