name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set Up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t simple-ci-cd-project .

    - name: Deploy Application
      run: |
        docker run -d -p 80:3000 simple-ci-cd-project
